### ISSUE TITLE
3.2 X_s bound inclusion

### ISSUE THREAD

**Issue by kevin-schumann** [automl-classroom/iML-ws21-ex03#2]
It seems like either the description of when x_s is included in an interval or the test case test_all_elements_included has an error.

The test case fails when x_s "is bigger than the lower bound and smaller [EQUALS] the upper bound" (lower < x_s <= upper). It doesn't fail for (lower <= x_s <= upper).

**Comment by felixmeyjr** [comment]
I have the same problem. When I have `X[:, s] >= lower_bound` the test case does not fail, if its only >, then it does. Any tipps? Thanks in advance

**Comment by kevin-schumann** [comment]
"However, make sure the elements in the first bound are included as well." You are not including all the elements for the first bound.

**Comment by felixmeyjr** [comment]
Ah, you are right. I've never noticed it, that the first row is missing. Thanks!
